
- name: ensure lenken directory
  file:
    path: /var/app/lenken
    state: directory

- name: Make application directory writable
  command: sudo chmod -R 777 /var/app/lenken

- name: ensure .ssh directory
  file:
    path: ~/.ssh
    state: directory
    mode: 400

- name: copy ssh key
  copy:
    src: dev_files/git_key
    dest: ~/.ssh/id_rsa

- name: change mode
  shell: chmod 400 ~/.ssh/id_rsa

- name: Ensure setfacl support is present
  package: name=acl

- name: clone repository
  git:
    repo: 'git@github.com:andela/lenken.git'
    dest: /var/app/lenken
    accept_hostkey: yes
    key_file: ~/.ssh/id_rsa

- name: clone current commit id
  command: git checkout {{ commit_id }}
  args:
    chdir: /var/app/lenken

- name: display
  shell: ls /var/app/lenken
  register: vagrant
- debug: var=vagrant.stdout_lines

- name: install requirements
  command: yarn install --ignore-engines
  args:
    chdir: /var/app/lenken
  environment:
    ENV: production
  ignore_errors: yes

- name: Copy lenken production config
  copy:
    src: dev_files/environment.prod
    dest: /var/app/lenken/src/environments/environment.prod.ts
    backup: yes

- name: Copy lenken envs config
  copy:
    src: dev_files/env
    dest: /var/app/lenken/src/envs.ts
    backup: yes

- name: build application
  command: yarn build
  args:
    chdir: /var/app/lenken
  environment:
    ENV: production
