- name: Ensure cert folder exists
  file:
    path: /etc/ssl/certs/
    state: directory

- name: Copy nginx configuration
  vars:
    domain: "{{ domain }}"
  template:
    src: files/nginx.j2
    dest: /etc/nginx/sites-enabled/default

- name: Copy nginx gzip config
  copy:
    src: ../../../../../common_files/gzip.conf
    dest: /etc/nginx/conf.d

- name: Copy crt certificate
  copy:
    src: ../../../../../common_files/certificate_crt
    dest: /etc/ssl/certs/certificate.crt

- name: copy key file
  copy:
    src: ../../../../../common_files/certificate_key
    dest: /etc/ssl/certs/certificate.key

- name: Test nginx
  command: nginx -t

- name: Restart nginx
  command: service nginx restart 
