- name: Install transport https
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - apt-transport-https
    - build-essential
    - lsb-release
    - ca-certificates

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: add dotdeb PPA
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: Add extra repositories
  apt_repository:
    repo: 'deb https://packages.sury.org/php/ jessie main'
    state: present

- name: Update system
  command: apt-get update

- name: Update installed packages
  apt:
    upgrade: dist

- name: Install git
  apt:
    name: git
    state: present