- name: disable apache
  command: systemctl disable apache2

- name: ensure service path exists
  file:
    path: /etc/systemd/system/
    state: directory

- name: copy production start script
  vars:
    branch: develop
    env_variable: "{{ env_variable }}"
    backend_build_commit: "{{ backend_build_commit }}"
  template:
    src: files/start.j2
    dest: /var/app/lenken_api/start.sh

- name: make file executable
  command: sudo chmod a+x /var/app/lenken_api/start.sh

- name: create lenken service
  copy:
    src: files/lenken.service
    dest: /etc/systemd/system/lenken.service

- name: Enable service
  command: systemctl enable lenken.service

- name: Start service
  service:
    name: lenken
    state: started
  