kind: Service
apiVersion: v1
metadata:
  #Service name
  name: lenken-backend
spec:
  selector:
    app: lenken-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer