apiVersion: apps/v1
kind: Deployment
metadata:
  name: lenken
  labels:
    #Project ID
    app: andela-learning
spec:
  #Run three instances of our application
  replicas: 3
  template:
    metadata:
      labels:
        app: andela-learning
    spec:
      #Container details
      containers:
        - name: lenken-frontend
          image: gcr.io/andela-learning/lenken-frontend:0.0.1
          imagePullPolicy: Always
          #Ports to expose
          ports:
          - containerPort: 4200