apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lenken-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - secretName: testsecret
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: lenken
          servicePort: 4200
      - path: /api/
        backend:
          serviceName: lenken-backend
          servicePort: 3000
      